name: Deploy Conductor

on:
  workflow_call:  # This allows other workflows to call this one

env:
  CONDUCTOR_REPO: conductor-oss/conductor
  CONDUCTOR_BRANCH: main

jobs:
  deploy-conductor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Conductor Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.CONDUCTOR_REPO }}
          ref: ${{ env.CONDUCTOR_BRANCH }}
          path: conductor

      - name: Start Conductor Services
        working-directory: conductor
        run: |
          docker compose -f docker/docker-compose.yaml up -d
          
      - name: Wait for Conductor to be ready
        run: |
          timeout=180  # 3 minutes timeout
          while ! curl -s http://localhost:8080/health > /dev/null; do
            if [ $timeout -le 0 ]; then
              echo "Timeout waiting for Conductor to start"
              exit 1
            fi
            echo "Waiting for Conductor to start... ($timeout seconds remaining)"
            sleep 5
            timeout=$((timeout-5))
          done
          echo "Conductor is ready!" 